packages:
  - packages/*

catalog:
  "@jest/globals": 29.7.0
  "@stryker-mutator/api": 8.6.0
  "@stryker-mutator/core": 8.6.0
  "@stryker-mutator/jest-runner": 8.6.0
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  jest-mock: 29.7.0
  lite-server: 2.6.1
  prettier: 3.2.4
  typescript: 5.3.3
  whatwg-fetch: 3.6.20
